"use client"
import { usePathname } from "next/navigation"
import Footer from "./footer"
import Navbar from "./navbar"
import "../styles/globals.css"


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  const pathname = usePathname();
  const noLayoutRoutes = ['/login', '/']

  const shouldShowLayout = !noLayoutRoutes.includes(pathname)
  return (
    <html lang="en">
      <head>
        <title>Mark 8</title>
        <meta name="description" content="Generated by Awesomity ltd" />
      </head>
      <body>
        {shouldShowLayout && <Navbar/>}
        {children}
        {shouldShowLayout && <Footer/>}
      </body>
    </html>
  )
}